### ISSUE TITLE
Modify MOA sniper rifle accuracy

### ISSUE THREAD

**Issue by Tarquin-Cassius** [51st-Mod-Team/dev-board-public#13]

**Comment by Tarquin-Cassius** [comment]
![Image](https://github.com/51st-Mod-Team/dev-board-public/assets/113350860/512d4bfd-0650-498f-b718-84c87c27c750)

**Comment by LegoManOnHash** [comment]
Working on this as we speak, almost done.

**Comment by LegoManOnHash** [comment]
Bug report complete.
