### ISSUE TITLE
Otaku Custom Helm

### ISSUE THREAD

**Issue by KakapoNZ** [51st-Mod-Team/dev-board-public#18]

**Comment by KakapoNZ** [comment]
![Image](https://github.com/51st-Mod-Team/dev-board-public/assets/157239919/f32e632d-1b2b-4078-8866-38526968439b)

**Comment by KakapoNZ** [comment]
![Image](https://github.com/51st-Mod-Team/dev-board-public/assets/157239919/0ebec8cf-203c-4b49-bdaa-1f8c726f4fe2)

**Comment by benkor1** [comment]
Added to Aux Mod, yet to be tested
