### ISSUE TITLE
Duck custom Armour

### ISSUE THREAD

**Issue by KakapoNZ** [51st-Mod-Team/dev-board-public#19]

**Comment by KakapoNZ** [comment]
![Image](https://github.com/51st-Mod-Team/dev-board-public/assets/157239919/ea471961-a19f-4d55-aa30-5d43470847d5)
![Image](https://github.com/51st-Mod-Team/dev-board-public/assets/157239919/01ef67f8-3bf8-432c-8807-e20cb0b96013)

**Comment by benkor1** [comment]
Added to aux mod, yet to be tested
