### ISSUE TITLE
ARF Armour updated with wear n tear

### ISSUE THREAD

**Issue by KakapoNZ** [51st-Mod-Team/dev-board-public#22]

**Comment by KakapoNZ** [comment]
![Image](https://github.com/51st-Mod-Team/dev-board-public/assets/157239919/36a63f3c-9bda-4b2c-86c3-59d94745334e)
![Image](https://github.com/51st-Mod-Team/dev-board-public/assets/157239919/70c520c5-43b8-42fa-b4e0-e68e32a5a940)

**Comment by benkor1** [comment]
added to aux mode, yet to be tested
