### ISSUE TITLE
Ducks Armour and Helm Updated with Wear n Tear

### ISSUE THREAD

**Issue by KakapoNZ** [51st-Mod-Team/dev-board-public#24]

**Comment by KakapoNZ** [comment]
![Image](https://github.com/51st-Mod-Team/dev-board-public/assets/157239919/91ad4e68-a161-4e80-9f63-5e076cd57246)
![Image](https://github.com/51st-Mod-Team/dev-board-public/assets/157239919/db855ffb-8de5-4090-9a17-e3fe54398efe)
![Image](https://github.com/51st-Mod-Team/dev-board-public/assets/157239919/68fcb793-661f-4552-b13c-713d01ebc685)

**Comment by Tarquin-Cassius** [comment]
Completed, Needs testing.
