### ISSUE TITLE
Dorn-1 Killshot custom helmet

### ISSUE THREAD

**Issue by CT-1036PAIN** [51st-Mod-Team/dev-board-public#41]
https://drive.google.com/file/d/12DqFpMsDcJMaQ2t4iRFrJStrUGy2s5AT/view?usp=sharing

**Comment by CT-1036PAIN** [comment]
https://drive.google.com/drive/folders/10nXFJlbsoqDH5p-grrNJhtPvniD08ESr?usp=sharing

**Comment by KakapoNZ** [comment]
completed and working
