### ISSUE TITLE
banshee laat/I (troop) 3as

### ISSUE THREAD

**Issue by 0462Rage** [51st-Mod-Team/dev-board-public#43]
![Interior_Diffuse](https://github.com/51st-Mod-Team/dev-board-public/assets/157238779/30721076-7bf0-455a-ab56-1f0c18764cb7)
![Weapon_Details_Diffuse](https://github.com/51st-Mod-Team/dev-board-public/assets/157238779/8e00f3b8-9026-4a9c-8a1e-55668eb08689)
![Weapons_Diffuse](https://github.com/51st-Mod-Team/dev-board-public/assets/157238779/d7865553-4c31-49d3-b3fc-0509dfb502e4)
![Wings_Diffuse](https://github.com/51st-Mod-Team/dev-board-public/assets/157238779/0226c839-1131-4e06-b772-f35b821c4ee4)
![Hull_Diffuse](https://github.com/51st-Mod-Team/dev-board-public/assets/157238779/604e68e1-27a0-41a4-bd82-168c88a76b17)

**Comment by 0462Rage** [comment]
link to doc with updated laat stuff as requested form kakapo

https://drive.google.com/drive/folders/1cUpz2sYNN6fvWb8_sEVlXQgQTDQzXr0Q?usp=sharing

**Comment by KakapoNZ** [comment]
completed tested and working
