### ISSUE TITLE
Aurek-4 Custom Armor

### ISSUE THREAD

**Issue by 51st-Mod-Team** [51st-Mod-Team/dev-board-public#5]

**Comment by 51st-Mod-Team** [comment]
![image](https://github.com/51st-Mod-Team/dev-board-public/assets/151185712/197bc782-40c0-499d-822c-013cddedab9e)

**Comment by CT-0043-Cabur** [comment]
![Image](https://github.com/51st-Mod-Team/dev-board-public/assets/157238840/d57a6cde-dc35-4619-a00a-73f580048e0d)
![Image](https://github.com/51st-Mod-Team/dev-board-public/assets/157238840/573f3b4b-277c-446c-b77d-dd6bd2264820)
![Image](https://github.com/51st-Mod-Team/dev-board-public/assets/157238840/ad5e840b-fba8-475d-a1f7-7eece2fec01f)

**Comment by benkor1** [comment]
Added to aux mod, yet to be tested
