### ISSUE TITLE
BX Commando - Overhaul

### ISSUE THREAD

**Issue by 51st-Mod-Team** [51st-Mod-Team/dev-board-public#6]

**Comment by 51st-Mod-Team** [comment]
- [x] Add custom BX uniform Standard.
- [x] Add custom BX Head (Invisible, only for armor values).
- [x] Add custom BX uniform Captain.
- [x] Add custom invis radio backpack
- [x] Add EMP protection to BX Weapons.
- [x] Add EMP protection BX Mags.
- [x] Modify armour values for BX uniform, 25% above standard clone troopers.

**Comment by Tarquin-Cassius** [comment]
- [x] Increase BX E5 mag count, from 30 > 50

**Comment by Tarquin-Cassius** [comment]
Fixed incorrect addons.
